[env]
# Version number shown in CLI and system tray. Override this by setting the
# version number on build/run (i.e. `VERSION_NUMBER="1.0.0" cargo run`).
VERSION_NUMBER = "0.0.0"

[target.aarch64-pc-windows-msvc]
linker = "lld-link"
rustflags = [
  "-Lnative=C:/Program Files (x86)/Windows Kits/10/lib/10.0.26100.0/um/arm64",
  "-Lnative=C:/Program Files (x86)/Windows Kits/10/lib/10.0.26100.0/ucrt/arm64",
  "-Lnative=C:/Program Files (x86)/Microsoft Visual Studio/18/BuildTools/VC/Tools/MSVC/14.50.35717/lib/arm64",
]
